### ISSUE TITLE
DG.subgraph does not output %DG{}

### ISSUE THREAD

**Issue by jdewar** [princemaple/dg#24]
I had a DG that was too large to print together so I did some edge snipping to make several components to display.  I found that I had to manually shove the output of DG.subgraph into a DG struct. 
```
components =
  dg
  |> DG.components()
  |> Enum.map(fn vertices ->
    new_dg = DG.subgraph(dg, vertices, keep_labels: true)
    %DG{dg: new_dg, opts: []}
  end)

components |> Enum.at(0) |> inspect |> Kino.Mermaid.new()
```

**Comment by princemaple** [comment]
Congrats. You probably used the library more than anyone else :) I never tried that function.

Do you want to send a PR? I will find the time to do it if you don't. Thanks for reporting.

**Comment by jdewar** [comment]
Took a swing at it. Being able to output mermaid into a Livebook cell was feature that had me use this library, thanks!
